# -*- coding: utf-8 -*-
"""Card data for the IV cannulation geometry primer. Lives in its own file and is
injected at build. Every numeral in `body` must be declared in CLAIMS."""

CARDS = [
{
 "id":"vein-depth","topic":"What you are measuring","title":"The vein depth","pic":"depth",
 "tldr":"Every calculation in this dictionary starts from the vein depth, so it matters that the reading moves with how you take it.",
 "lede":"Push a stick into a pond to find the bottom, and the answer depends on how hard you push.",
 "ctrl":[{"k":"Probe pressure","key":"press","opts":[[0,"Light"],[1,"Firm"]]},
         {"k":"Caliper lands on","key":"targ","opts":[[0,"Front wall"],[1,"Lumen centre"]]}],
 "body":[
  {"p":"Depth is measured straight down from the probe face to the front wall of the vein, not along the needle path and not to the middle of the lumen. Work the two controls above and watch the caliper: the same vein gives three different answers while it stays exactly where it is."},
  {"h":"Which surface you count"},
  {"p":"A reading taken to the middle of the lumen gives 6.5 mm on this vein, against 5.0 mm to the front wall. Both papers behind this dictionary measure to the front wall, and every calculation later on assumes it, so the extra 1.5 mm of a centre reading would carry into every rule that uses the depth."},
  {"h":"How hard you are pressing"},
  {"p":"Turn the pressure up and the reading falls to 3.5 mm, and watch what actually moves: the probe presses into the skin, the soft tissue between the two thins, and the vein flattens because it is a low pressure vessel and it gives. The depth scale slides down with the probe face, which is where the smaller number comes from. Forrest and Keys ask for enough gel and light pressure so that veins stay round and their true diameter can be read."},
  {"h":"What a monitor shows instead"},
  {"p":"A real screen never shows you the probe. It fixes the transducer face at the top of the image and measures everything down from there, so as you press, the vein appears to rise when it has not. The window above is drawn from the tissue's side instead, so you can watch where the number goes."},
  {"h":"Why this card comes first"},
  {"p":"Everything after this takes the depth as given and turns it into a catheter length. A depth that moved with the measurement will move every answer built on it, and it is better to know that before the arithmetic starts."}],
 "src":["Both held papers measure perpendicular depth to the front wall. Moustaqim-Barrette, Riehm, Parra, Munshey. Pediatric Anesthesia 2026;36:135-144, doi 10.1111/pan.70076. Forrest, Keys. BJA Education 2026;26(8):344-353, doi 10.1016/j.bjae.2026.05.003.",
        "The probe pressure guidance is Forrest and Keys. The amount of compression drawn is illustrative: neither paper gives a magnitude, and the split between tissue thinning and vein flattening is chosen rather than measured.",
        "The comparison with a lumen-centre reading is this dictionary's own arithmetic on the vein drawn above."]},
{
 "id":"gauge-length","topic":"The catheter","title":"Gauge and length","pic":"devices",
 "tldr":"Two independent numbers on the same device, and only one of them is in the formula.",
 "lede":"A drinking straw can be long or it can be wide, and neither one tells you about the other.",
 "ctrl":[{"k":"Catheter length","key":"len","opts":[[0,"19 mm"],[1,"25 mm"],[2,"32 mm"],[3,"45 mm"]]}],
 "body":[
  {"p":"Gauge is the bore and length is the length, and the stock shows they move independently: 24G comes at 19 mm and at 32 mm with the same 0.7 mm outer diameter, and 22G comes at 25 mm and at 45 mm with the same 0.9 mm. The four above are drawn at true scale against each other."},
  {"h":"Which one the geometry uses"},
  {"tab":[["The number","What it drives"],["Gauge \u2192 bore","the width rule, near the end"],["Length \u2192 depth","every rule until then"]]},
  {"p":"When a rule asks for a number from here on, it is asking for millimetres of catheter. Bore comes back at the end, where it also decides how fast the line runs."},
  {"h":"Longer without wider"},
  {"p":"The two get spoken about together, so it is worth separating them: choosing a longer device to serve a deeper vein does not commit you to a wider one, and the four lengths above span 19 to 45 mm across two gauges."}],
 "src":["Lengths, outer diameters and flow rates from Moustaqim-Barrette Table 1 and Forrest and Keys Table 1, cited rather than reproduced. The drawing is generated from those figures."]},
{
 "id":"entry-angle","topic":"The catheter","title":"The entry angle","pic":"angleTri",
 "tldr":"The angle between needle and skin, and the reason the needle travels further than the depth.",
 "lede":"A ramp up to a doorway is longer than the step it replaces, and the shallower it is the longer it gets.",
 "ctrl":[{"k":"Entry angle","key":"angle","opts":[[45,"45\u00b0"],[30,"30\u00b0"],[20,"20\u00b0"]]}],
 "body":[
  {"p":"Depth is measured straight down and the needle is not: it enters at an angle, so the distance it travels through tissue to the vein is the depth divided by the sine of that angle. Move the control and watch the lit stretch of shaft against the depth beside it."},
  {"h":"The three numbers worth carrying"},
  {"tab":[["Entry angle","Path \u00f7 depth"],["45\u00b0","1.4\u00d7"],["30\u00b0","2.0\u00d7"],["20\u00b0","2.9\u00d7"]]},
  {"h":"Why the multiplier matters"},
  {"p":"Every rule in this dictionary is about how much catheter is left over once that path has been paid for, and the steeper the entry, the less the path costs."}],
 "src":["The 1.4 multiplier at 45 degrees is Moustaqim-Barrette's own figure and their length table is built on it. The 30 and 20 degree multipliers extend their construction and are this dictionary's arithmetic."]},
{
 "id":"intraluminal","topic":"The rule","title":"Intraluminal length","pic":"track","marks":["lumen"],
 "tldr":"The length of catheter that ends up inside the vein, which is what the outcome data measured.",
 "lede":"How much of a nail is in the wall decides whether the picture stays up. The length printed on the box does not.",
 "ctrl":[{"k":"Catheter length","key":"len","opts":[[0,"19 mm"],[1,"25 mm"],[2,"32 mm"],[3,"45 mm"]]}],
 "body":[
  {"p":"Once it is in, the catheter has two parts: the stretch outside the vein, crossing skin and fat, and the stretch inside the lumen, which is the only part doing anything. Move the length control and watch both."},
  {"h":"What the data says"},
  {"p":"In adults, catheters with under 30% of their length inside the vein failed in every case, with a median working life of 3.7 hours. Between 30 and 64%, 32% failed and the median was 22.1 hours. At 65% or more, no failures were reported."},
  {"h":"Where those figures come from"},
  {"p":"Those are adult figures from two secondary analyses, and this dictionary holds neither primary paper. What is paediatric is the consequence: infiltration is the leading cause of line failure in children, at around 10% of lines overall and 20 to 25% once therapy runs past four days."}],
 "src":["Second-hand and adult. Forrest and Keys report the failure figures from Bahl 2024 and Pandurangadu 2018; neither primary is held here. The paediatric infiltration figures are Forrest and Keys' own."]},
{
 "id":"rule-65","topic":"The rule","title":"The 65% rule","pic":"track","marks":["m65"],
 "tldr":"At least 65% of the catheter inside the vein, which leaves 35% for the journey.",
 "lede":"A budget with a single line on it: 35% of the catheter has to cover everything between skin and lumen.",
 "ctrl":[{"k":"Entry angle","key":"angle","opts":[[45,"45\u00b0"],[30,"30\u00b0"],[20,"20\u00b0"]]}],
 "body":[
  {"p":"Written out, the constraint is one line: the path from skin to front wall has to fit inside 35% of the catheter's length. Move the angle and watch the mark on the shaft. When the mark sits on the skin, the rule is met with nothing to spare."},
  {"h":"Turned around, it sizes the catheter"},
  {"p":"The shortest catheter that satisfies it is the depth divided by 0.35 times the sine of the angle."},
  {"tab":[["Entry angle","Min length \u00f7 depth"],["45\u00b0","4.0\u00d7"],["30\u00b0","5.7\u00d7"],["20\u00b0","8.4\u00d7"]]},
  {"p":"Moustaqim-Barrette work the same sum for two depths: 0.5 cm at 45 degrees needs at least 2 cm, and 1 cm needs at least 4 cm."},
  {"h":"What kind of rule this is"},
  {"p":"It is a geometric recommendation inside an educational review, cited there from a narrative review this dictionary does not hold, and no trial has compared catheters placed to it against catheters placed without it."}],
 "src":["Second-hand. Moustaqim-Barrette state the rule citing Nakayama 2020, a narrative review not held here. Their two worked examples are reproduced exactly by the formula above."]},
{
 "id":"reach","topic":"The rule","title":"Reach","pic":"arc",
 "tldr":"The deepest vein a given catheter can serve while still meeting the rule.",
 "lede":"A ladder's reach is how high it gets once it is leaning, and that is less than its length.",
 "ctrl":[{"k":"Catheter length","key":"len","opts":[[0,"19 mm"],[1,"25 mm"],[2,"32 mm"],[3,"45 mm"]]}],
 "body":[
  {"p":"For a catheter of length L at angle theta, reach is 0.35 times L times the sine of theta. Reach is a perpendicular depth, the number you read off the screen, and the mistake to avoid is reading it as a distance along the needle. Each arc above is one catheter's reach as the angle sweeps from flat to vertical."},
  {"h":"The four stock lengths, at 45 degrees"},
  {"tab":[["Catheter","Reach at 45\u00b0"],["19 mm","4.7 mm"],["25 mm","6.2 mm"],["32 mm","7.9 mm"],["45 mm","11.1 mm"]]},
  {"p":"Paediatric veins are usually under 10 mm deep, so three of the four are working near their limit before anything else has gone wrong."},
  {"h":"A rounding in the source"},
  {"p":"Moustaqim-Barrette's table puts a 32 mm catheter at up to 0.8 cm. The formula gives 7.92 mm, so the band is optimistic by 0.08 mm at its top, a small margin that exists because the table was rounded."}],
 "src":["Derived. The formula reproduces both of Moustaqim-Barrette's worked pairs. Their length table is cited and described rather than redrawn: the paper is CC BY-NC-ND. The word reach is this dictionary's own; neither paper names the quantity."]},
{
 "id":"shallowing","topic":"The rule","title":"Dropping the angle","pic":"arc","wedge":True,
 "tldr":"Going from 45 to 20 degrees costs half the reach, and the same half for every catheter.",
 "lede":"Lay a ladder flatter and it reaches less high, by the same fraction whatever the ladder.",
 "ctrl":[{"k":"Entry angle","key":"angle","opts":[[45,"45\u00b0"],[30,"30\u00b0"],[20,"20\u00b0"]]}],
 "body":[
  {"p":"The loss is the ratio of two sines, so the length cancels and so does the depth. Dropping from 45 to 30 degrees costs 29.3% of reach, and dropping to 20 costs 51.6%, identically for all four catheters to four decimal places."},
  {"h":"Why that is useful"},
  {"p":"It means the sum does not have to be redone per device. Whatever you were reaching at 45 degrees, you keep a little under half of it at 20."},
  {"h":"Watch the arcs"},
  {"p":"Move the control and all four shrink together while nothing about the catheters changes."}],
 "src":["Derived. The invariance is this dictionary's own result and is checked across all four lengths."]},
{
 "id":"judging-angle","topic":"The rule","title":"Judging the angle","pic":"track","marks":["m65"],
 "tldr":"Nobody reads the angle off a screen, and it is the variable the whole subject turns on.",
 "lede":"Nobody measures how steeply they are holding the needle, and everybody has an opinion about it.",
 "ctrl":[{"k":"Angle","key":"angle","opts":[[45,"Aiming 45\u00b0"],[30,"Likely 30\u00b0"],[20,"Maybe 20\u00b0"]]}],
 "body":[
  {"p":"Moustaqim-Barrette put it plainly: only a qualitative gauge of needle angle relative to skin is available, so catheter lengths greater than the minimum should be selected. Forrest and Keys write that 45 degrees is difficult to judge and maintain, that 30 degrees or less is probably more common in practice, and that longer catheters are therefore generally preferable."},
  {"h":"What the control above is showing"},
  {"p":"The chips are three readings of the same hand: the angle you are aiming for and the two you may actually be holding. Pick one and the card draws it. The mark on the shaft walks out toward the skin as the angle falls, and once it passes the skin the rule is no longer met."},
  {"h":"The practical consequence"},
  {"p":"Two independent groups reach the same advice from the same limitation: take the number the calculation gives you and go longer than it."}],
 "src":["Held, both papers, quoted closely."]},
{
 "id":"flattening","topic":"The rule","title":"Flattening the tip","pic":"stages",
 "tldr":"The angle changes once the vein has been entered, so no single number describes it.",
 "lede":"A plane comes in nose up and then puts its wheels down flat, and those are two different problems.",
 "ctrl":[{"k":"Stage","key":"stage","opts":[[0,"At the skin"],[1,"At entry"],[2,"Flattened"]]}],
 "body":[
  {"p":"Entry angle and resting angle are different measurements pulling in opposite directions: a steeper entry buys reach and helps keep the tip aligned with the beam, while a flatter resting angle keeps the tip in the upper half of the lumen and away from the back wall."},
  {"h":"The move itself"},
  {"p":"Moustaqim-Barrette advise flattening the needle angle once the tip is in the lumen and keeping it in the upper half of the vessel. Flatten only after a millimetre or two of advance: with the tip barely through the wall, dropping the hub pivots it straight back out of the vein. Step through the three stages above."},
  {"h":"One number attached to it"},
  {"p":"Forrest and Keys report that tip angles above 5 degrees carried a higher phlebitis risk. They offer it as a proposed mechanism for why longer catheters last longer rather than as a demonstrated cause."}],
 "src":["Held for the technique. The 5 degree figure is second-hand, cited by Forrest and Keys from a paper not held here."]},
{
 "id":"floor-275","topic":"The other rule","title":"The 27.5 mm minimum","pic":"track","marks":["abs"],
 "tldr":"A fixed length of catheter in the vein, rather than a fraction of it.",
 "lede":"A minimum deposit does not scale with the price of the house.",
 "ctrl":[{"k":"Entry angle","key":"angle","opts":[[45,"45\u00b0"],[30,"30\u00b0"],[20,"20\u00b0"]]}],
 "body":[
  {"p":"Forrest and Keys size catheters against an absolute: 27.5 mm of catheter inside the vein, whatever the catheter is. The minimum length becomes 27.5 mm plus the skin-to-vein path, so 27.5 plus the depth divided by the sine of the angle."},
  {"h":"Where it comes from"},
  {"p":"It comes from the same adult intravascular-length work as the 65% figure: one group read the finding as a proportion and the other as a length, so the two are not rival traditions."},
  {"h":"The mark on the shaft"},
  {"p":"Move the angle and watch it. This mark does not move when the catheter changes length, and the next card is about what that costs."}],
 "src":["Second-hand, the same two adult analyses as the intraluminal length card. This dictionary's reconstruction reproduces 17 of the 18 cells Forrest and Keys print; their 0.25 cm at 45 degree cell computes to 31.04 mm and prints 31. Quote their table rather than the formula."]},
{
 "id":"which-governs","topic":"The other rule","title":"Which rule governs","pic":"track","marks":["m65","abs"],
 "tldr":"A fraction of a short catheter is a short length, and that is where the two part company.",
 "lede":"10% off is a bargain on a car and nothing at all on a coffee.",
 "ctrl":[{"k":"Catheter length","key":"len","opts":[[0,"19 mm"],[1,"25 mm"],[2,"32 mm"],[3,"45 mm"]]}],
 "body":[
  {"p":"Both marks sit on one shaft, and the binding rule is whichever lies further from the tip: 0.65 times the length against a flat 27.5 mm, crossing at 42.3 mm."},
  {"h":"Below the crossover"},
  {"p":"The absolute governs here: a 19 or 25 mm catheter cannot hold 27.5 mm inside a vein at any angle or any depth, and a 32 mm catheter satisfies it only out to 3.18 mm of depth at 45 degrees."},
  {"h":"Above it"},
  {"p":"The proportion governs, and of the four stock lengths, 45 mm is the first where 65% of the catheter comes to more than 27.5 mm."},
  {"h":"What to do with that"},
  {"p":"Both criteria come from the same adult data and neither has been tested in children, so for now the useful part is knowing which one is doing the work in a given device."}],
 "src":["Derived from the two rules as each paper states them."]},
{
 "id":"cvr","topic":"Width, not length","title":"Catheter-vein ratio","pic":"cross",
 "tldr":"The other geometric constraint, and this one is about width.",
 "lede":"A cork too wide for the bottle is a different problem from a cork too short.",
 "ctrl":[{"k":"Threshold","key":"thr","opts":[[45,"45%"],[40,"40%"],[33,"33%"]]}],
 "body":[
  {"p":"The rule is the catheter's outer diameter against the vein's diameter, and the sources disagree about the number. mini-MAGIC recommends 45% or less. The European ERPIUP consensus suggests 33% or less for long peripheral devices. Moustaqim-Barrette use under 0.4, excluding neonates, and 0.33 or less in premature neonates."},
  {"h":"What the disagreement costs"},
  {"p":"At 45% a 22G needs a 2.0 mm vein, and at 33% the same device needs 2.7 mm. Switch the threshold above and watch which gauges still fit."},
  {"h":"Measured under what"},
  {"p":"The diameter is read off the same screen, under the same probe pressure, as the depth. Flattening a vein widens it, so a vein measured under pressure will pass a ratio it would fail when round. See the card on the vein depth. The tourniquet matters the same way: Forrest and Keys' minimum-diameter table is for veins measured without one, and Moustaqim-Barrette describe a tight tourniquet distending the vein, so a ratio passed under a tourniquet may not hold once it comes off."}],
 "src":["Held; the three thresholds are each cited to their own source. Forrest and Keys' minimum-diameter table reproduces exactly from outer diameter divided by threshold, all eight cells.",
        "The no-tourniquet measurement state is Forrest and Keys. The distending effect of a tight tourniquet is Moustaqim-Barrette, who also caution against tight tourniquets in premature babies and infants."]},
{
 "id":"flow-dwell","topic":"Width, not length","title":"Gauge and flow","pic":"devices","flow":True,
 "tldr":"Length is bought with flow, at an unchanged bore.",
 "lede":"A longer hose at the same width delivers less, and the tap has not moved.",
 "ctrl":[{"k":"Catheter length","key":"len","opts":[[0,"19 mm"],[1,"25 mm"],[2,"32 mm"],[3,"45 mm"]]}],
 "body":[
  {"p":"Bore comes back here: going from a 24G at 19 mm to a 24G at 32 mm costs 22.7% of maximum flow at an identical 0.7 mm. A 22G from 25 to 45 mm costs 25.7% at an identical 0.9 mm."},
  {"h":"The two questions are separate"},
  {"p":"Gauge decides delivery rate and length decides how long the line lasts. Choosing the longer device to satisfy a geometric rule therefore has a price, and the price is paid in flow."},
  {"h":"Where it bites"},
  {"p":"On a maintenance infusion it rarely matters, but the same line may have to carry a bolus, blood or a resuscitation volume, and that is a decision about the case rather than about the vein."}],
 "src":["Held. Flow figures from Moustaqim-Barrette Table 1, cited. The percentages are this dictionary's arithmetic on their figures."]},
{
 "id":"out-of-plane","topic":"The screen","title":"Out of plane","pic":"planes",
 "tldr":"In short axis the needle is a dot, and the dot looks the same anywhere along the shaft.",
 "lede":"Cut a length of spaghetti anywhere and the cut end looks identical; only past the end is there nothing to cut.",
 "ctrl":[{"k":"Scan plane","key":"plane","opts":[[14,"On the shaft"],[30.2,"At the tip"],[33,"Past the tip"]]}],
 "body":[
  {"p":"An ultrasound image is one thin slice. Held across the vein it cuts the needle too, so the whole device appears as a single bright dot, and a slice through the shaft gives the same dot as a slice through the tip. Drag the plane along the catheter above and watch the screen below it."},
  {"h":"What the screen cannot say"},
  {"p":"The upper picture has the whole catheter in view, so the tip is never in doubt there. The screen below has one slice, and while that slice sits over steel the dot neither grows nor shrinks as the plane moves along the shaft. Only the depth changes: the dot deepens down the entry slope, then rides level in the middle of the lumen."},
  {"h":"Telling tip from shaft"},
  {"p":"The dot exists where the plane crosses the catheter and nowhere else, so sliding past the tip makes it vanish, and sliding back brings it back. Moustaqim-Barrette's strategy table states it directly: once the tip is reached, any further probe translation will cause the needle to disappear."},
  {"h":"Where this dictionary stops"},
  {"p":"Both papers centre this short axis, out of plane view in children. The technique built on the vanishing dot, dynamic needle tip positioning, moves probe and needle in alternating small steps, and it is a separate subject, out of scope here with the rest of technique."}],
 "src":["Held. Forrest and Keys build their insertion sequence on sliding the probe until the dot shrinks to the tip, and Moustaqim-Barrette confirm tip against shaft by translating the probe until the dot disappears and reappears.",
        "The pictures are generated from this card's own geometry and are not taken from either paper's figures."]},
{
 "id":"limits","topic":"The limits","title":"What geometry misses","pic":"trackStill",
 "links":[["Moustaqim-Barrette 2026 \u00b7 Pediatric Anesthesia","https://doi.org/10.1111/pan.70076"],["Forrest & Keys 2026 \u00b7 BJA Education","https://doi.org/10.1016/j.bjae.2026.05.003"]],
 "tldr":"The formula assumes a straight path into a vein that does not move.",
 "lede":"A map that shows every road still tells you nothing about the traffic.",
 "body":[
  {"p":"The model behind every card here assumes a straight needle track, a vein that neither rolls nor compresses, an angle nobody can measure, and a depth taken under whatever pressure the probe was applying. Moustaqim-Barrette describe needle deflection after the skin as common in children with more subcutaneous tissue."},
  {"h":"The larger part"},
  {"p":"Most of cannulation is haptic: the change in resistance as a wall gives, the feel of a vein that rolls away, knowing when to stop and move. No diagram teaches any of it, and this dictionary does not pretend otherwise."},
  {"h":"What is out of scope here"},
  {"p":"Technique, including needle tip tracking under ultrasound, which is a separate subject; site selection; and everything about the child in front of you."},
  {"h":"And the provenance"},
  {"p":"Both thresholds are second-hand, the intravascular-length data behind them is adult, and the 65% rule is a geometric recommendation rather than outcome evidence. That is stated on each card that uses them, and it is worth restating once at the end."}],
 "src":["Held for needle deflection and for the haptic limit. The rest is a summary of provenance already stated card by card."]},
]

# Every numeral that appears in body prose, with its class and its check.
CLAIMS = {
 "6.5":"engine","5.0":"engine","1.5":"engine","3.5":"engine",
 "0.7":"literature","0.9":"literature","19":"control","25":"control","32":"control","45":"control",
 "24":"literature","22":"literature","3":"structural","2":"structural",
 "1.4":"literature","2.9":"derived","30":"control","20":"control",
 "65":"criterion","35":"criterion","0.35":"criterion","4.0":"derived","5.7":"derived","8.4":"derived",
 "0.5":"literature","1":"literature","4":"literature",
 "3.7":"literature","64":"literature","22.1":"literature","10":"literature","4.7":"derived",
 "6.2":"derived","7.9":"derived","7.92":"derived","11.1":"derived","0.8":"literature","0.08":"derived",
 "29.3":"derived","51.6":"derived","27.5":"criterion","2.75":"criterion","42.3":"derived",
 "3.18":"derived","0.65":"criterion","17":"structural","18":"structural","0.25":"literature",
 "31.04":"derived","31":"literature","5":"literature","40":"criterion","33":"criterion","0.4":"criterion",
 "0.33":"criterion","2.0":"derived","2.7":"derived","22.7":"derived","25.7":"derived","8":"structural",
}
